version: '3'

services:
  db:
    image: postgres:14
    container_name: postgres
    ports:
      - 15432:5432
    volumes:
      - db_practice:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
volumes:
  db_practice:

